Add generator brazilian phone number
elixirs/faker pull request #356
Opened 2020-08-08 06:10 UTC by NetonD

Add following categories to portugues brazilian:

- Phone

2020-08-08 07:17 UTC, NetonD commented
Is my first contribuition to an open source project, sorry for this, but I need help to undestain what is wrong.

2020-08-11 12:54 UTC, anthonator commented on lib/faker/phone/pt_br.ex
> +  end
Could you provide some documentation with examples for `number_with_region/1`?

2020-08-11 12:55 UTC, anthonator commented
Thank you for contributing! Could you please update `CHANGELOG.md`?

2020-09-24 22:28 UTC, vbrazo commented on lib/faker/phone/pt_br.ex
> +  Function to generate brazilians phone  number.
```suggestion
  Function to generate brazilians phone number.
```

2020-10-19 12:38 UTC, anthonator requested changes

2020-10-19 12:38 UTC, anthonator commented on lib/faker/phone/pt_br.ex
> +  Function to generate brazilians phone  number.
This still needs to be fixed.

2021-09-18 01:21 UTC, vbrazo approved these changes
LGTM

2021-09-18 12:46 UTC, anthonator approved these changes

2021-09-18 12:46 UTC, merged